apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://localhost:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: home
      defaultBucket: weather
    secureJsonData:
      token: <INFLUXDB_TOKEN>
